services:
  - name: flask-backend
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: chatgpt  # Make sure this matches your actual MongoDB database name
          type: mongodb
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python app.py

