services:
  - name: flask-backend
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: your-mongodb-database-name
          type: mongodb
    buildCommand: python -m pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:5000 app:app


